<?php

declare(strict_types=1);

namespace PdfLib\Form;

use PdfLib\Parser\Object\PdfArray;
use PdfLib\Parser\Object\PdfDictionary;
use PdfLib\Parser\Object\PdfName;
use PdfLib\Parser\Object\PdfNumber;
use PdfLib\Parser\Object\PdfReference;
use PdfLib\Parser\Object\PdfStream;
use PdfLib\Parser\Object\PdfString;
use PdfLib\Writer\PdfWriter;

/**
 * Writes form fields to PDF output.
 *
 * Handles creation of:
 * - Widget annotation dictionaries
 * - Appearance streams (XObjects)
 * - AcroForm dictionary with /Fields array
 * - Standard fonts for form rendering
 *
 * @example
 * ```php
 * $writer = new PdfWriter();
 * $formWriter = new FormWriter($writer);
 *
 * // Add fields
 * $formWriter->addField($textField);
 * $formWriter->addField($checkbox);
 * $formWriter->addRadioGroup($radioGroup);
 *
 * // Build AcroForm
 * $acroFormRef = $formWriter->buildAcroForm();
 *
 * // Get annotations for each page
 * $pageAnnots = $formWriter->getPageAnnotations();
 * ```
 */
final class FormWriter
{
    private PdfWriter $writer;

    /** @var array<string, FormField> */
    private array $fields = [];

    /** @var array<string, RadioButtonGroup> */
    private array $radioGroups = [];

    /** @var array<int, PdfReference> Field references */
    private array $fieldRefs = [];

    /** @var array<int, array<int, PdfReference>> Page number => annotation references */
    private array $pageAnnotations = [];

    /** @var array<string, PdfReference> Font references by name */
    private array $fontRefs = [];

    private ?PdfReference $acroFormRef = null;

    private bool $needsAppearances = false;

    public function __construct(PdfWriter $writer)
    {
        $this->writer = $writer;
    }

    /**
     * Add a form field.
     */
    public function addField(FormField $field): self
    {
        $this->fields[$field->getName()] = $field;
        return $this;
    }

    /**
     * Add a radio button group.
     */
    public function addRadioGroup(RadioButtonGroup $group): self
    {
        $this->radioGroups[$group->getName()] = $group;
        return $this;
    }

    /**
     * Add all fields from a collection.
     */
    public function addCollection(FormFieldCollection $collection): self
    {
        foreach ($collection->all() as $field) {
            $this->addField($field);
        }
        return $this;
    }

    /**
     * Set whether appearances need to be regenerated by the viewer.
     */
    public function setNeedsAppearances(bool $needs): self
    {
        $this->needsAppearances = $needs;
        return $this;
    }

    /**
     * Build all form objects and return AcroForm reference.
     */
    public function buildAcroForm(): PdfReference
    {
        // Create standard fonts
        $this->createStandardFonts();

        // Process individual fields
        foreach ($this->fields as $field) {
            $this->processField($field);
        }

        // Process radio button groups
        foreach ($this->radioGroups as $group) {
            $this->processRadioGroup($group);
        }

        // Build and return AcroForm dictionary
        return $this->buildAcroFormDictionary();
    }

    /**
     * Process a single form field.
     */
    private function processField(FormField $field): void
    {
        // Get page reference placeholder (will be set when integrating with document)
        $pageRef = null;

        // Build widget dictionary
        $widgetDict = $field->toWidgetDictionary($pageRef);

        // Generate and add appearance stream
        $appearanceRef = $this->createAppearanceStream($field);
        if ($appearanceRef !== null) {
            $apDict = new PdfDictionary();
            $apDict->set('N', $appearanceRef);
            $widgetDict->set('AP', $apDict);
        }

        // Add widget as object
        $fieldRef = $this->writer->addObject($widgetDict);
        $this->fieldRefs[] = $fieldRef;

        // Track page annotation
        $page = $field->getPage();
        if (!isset($this->pageAnnotations[$page])) {
            $this->pageAnnotations[$page] = [];
        }
        $this->pageAnnotations[$page][] = $fieldRef;
    }

    /**
     * Process a radio button group.
     */
    private function processRadioGroup(RadioButtonGroup $group): void
    {
        $options = $group->getOptions();
        if (empty($options)) {
            return;
        }

        // Create child widget references
        $kidRefs = [];

        foreach ($options as $option) {
            // Create appearances for both states
            $selectedAppRef = $this->createRadioAppearanceStream($option, true);
            $unselectedAppRef = $this->createRadioAppearanceStream($option, false);

            // Build widget dictionary for option
            $widgetDict = $option->toWidgetDictionary(null);

            // Add appearance streams
            if ($selectedAppRef !== null && $unselectedAppRef !== null) {
                $apDict = new PdfDictionary();

                // Normal appearance dictionary with named states
                $nDict = new PdfDictionary();
                $nDict->set($option->getOptionValue(), $selectedAppRef);
                $nDict->set('Off', $unselectedAppRef);
                $apDict->set('N', $nDict);

                $widgetDict->set('AP', $apDict);
            }

            // Add widget as object
            $optionRef = $this->writer->addObject($widgetDict);
            $kidRefs[] = $optionRef;

            // Track page annotation
            $page = $option->getPage();
            if (!isset($this->pageAnnotations[$page])) {
                $this->pageAnnotations[$page] = [];
            }
            $this->pageAnnotations[$page][] = $optionRef;
        }

        // Build parent field dictionary
        $parentDict = $group->toFieldDictionary();
        $parentDict->set('Kids', new PdfArray($kidRefs));

        $parentRef = $this->writer->addObject($parentDict);
        $this->fieldRefs[] = $parentRef;

        // Update kids to point to parent
        foreach ($kidRefs as $kidRef) {
            $obj = $this->writer->getObject($kidRef->getObjectNumber());
            if ($obj instanceof PdfDictionary) {
                $obj->set('Parent', $parentRef);
            }
        }
    }

    /**
     * Create appearance stream for a field.
     */
    private function createAppearanceStream(FormField $field): ?PdfReference
    {
        $content = $field->generateAppearance();
        if (empty($content)) {
            return null;
        }

        $width = $field->getWidth();
        $height = $field->getHeight();

        // Build resources dictionary
        $resources = $this->buildAppearanceResources($field);

        // Create form XObject
        $streamDict = new PdfDictionary();
        $streamDict->set('Type', PdfName::create('XObject'));
        $streamDict->set('Subtype', PdfName::create('Form'));
        $streamDict->set('FormType', PdfNumber::int(1));
        $streamDict->set('BBox', PdfArray::fromValues([
            PdfNumber::real(0),
            PdfNumber::real(0),
            PdfNumber::real($width),
            PdfNumber::real($height),
        ]));
        $streamDict->set('Resources', $resources);

        $stream = new PdfStream($streamDict, $content);
        return $this->writer->addObject($stream);
    }

    /**
     * Create appearance stream for a radio button option.
     */
    private function createRadioAppearanceStream(RadioButtonOption $option, bool $selected): ?PdfReference
    {
        $content = $selected
            ? $option->generateSelectedAppearance()
            : $option->generateUnselectedAppearance();

        if (empty($content)) {
            return null;
        }

        $width = $option->getWidth();
        $height = $option->getHeight();

        // Build resources dictionary
        $resources = new PdfDictionary();

        // Create form XObject
        $streamDict = new PdfDictionary();
        $streamDict->set('Type', PdfName::create('XObject'));
        $streamDict->set('Subtype', PdfName::create('Form'));
        $streamDict->set('FormType', PdfNumber::int(1));
        $streamDict->set('BBox', PdfArray::fromValues([
            PdfNumber::real(0),
            PdfNumber::real(0),
            PdfNumber::real($width),
            PdfNumber::real($height),
        ]));
        $streamDict->set('Resources', $resources);

        $stream = new PdfStream($streamDict, $content);
        return $this->writer->addObject($stream);
    }

    /**
     * Build resources dictionary for appearance stream.
     */
    private function buildAppearanceResources(FormField $field): PdfDictionary
    {
        $resources = new PdfDictionary();

        // Add font resources
        $fontDict = new PdfDictionary();

        // Standard fonts used by form fields
        if (isset($this->fontRefs['Helvetica'])) {
            $fontDict->set('Helv', $this->fontRefs['Helvetica']);
        }
        if (isset($this->fontRefs['ZapfDingbats'])) {
            $fontDict->set('ZaDb', $this->fontRefs['ZapfDingbats']);
        }

        // Add field-specific fonts
        if ($field instanceof TextField || $field instanceof DropdownField || $field instanceof ListBoxField) {
            // These fields may use custom fonts
            if (isset($this->fontRefs['Helvetica'])) {
                $fontDict->set('Helvetica', $this->fontRefs['Helvetica']);
            }
        }

        if ($fontDict->count() > 0) {
            $resources->set('Font', $fontDict);
        }

        return $resources;
    }

    /**
     * Create standard fonts used by form fields.
     */
    private function createStandardFonts(): void
    {
        // Helvetica - standard text font
        $helvetica = new PdfDictionary();
        $helvetica->set('Type', PdfName::create('Font'));
        $helvetica->set('Subtype', PdfName::create('Type1'));
        $helvetica->set('BaseFont', PdfName::create('Helvetica'));
        $helvetica->set('Encoding', PdfName::create('WinAnsiEncoding'));
        $this->fontRefs['Helvetica'] = $this->writer->addObject($helvetica);

        // ZapfDingbats - for checkmarks and symbols
        $zapf = new PdfDictionary();
        $zapf->set('Type', PdfName::create('Font'));
        $zapf->set('Subtype', PdfName::create('Type1'));
        $zapf->set('BaseFont', PdfName::create('ZapfDingbats'));
        $this->fontRefs['ZapfDingbats'] = $this->writer->addObject($zapf);
    }

    /**
     * Build the AcroForm dictionary.
     */
    private function buildAcroFormDictionary(): PdfReference
    {
        $acroForm = new PdfDictionary();

        // Fields array
        $acroForm->set('Fields', new PdfArray($this->fieldRefs));

        // Needs appearances flag
        if ($this->needsAppearances) {
            $acroForm->set('NeedAppearances', \PdfLib\Parser\Object\PdfBoolean::create(true));
        }

        // Default resources
        $dr = new PdfDictionary();
        $fontDict = new PdfDictionary();
        if (isset($this->fontRefs['Helvetica'])) {
            $fontDict->set('Helv', $this->fontRefs['Helvetica']);
        }
        if (isset($this->fontRefs['ZapfDingbats'])) {
            $fontDict->set('ZaDb', $this->fontRefs['ZapfDingbats']);
        }
        if ($fontDict->count() > 0) {
            $dr->set('Font', $fontDict);
        }
        $acroForm->set('DR', $dr);

        // Default appearance string
        $acroForm->set('DA', PdfString::literal('/Helv 12 Tf 0 g'));

        // Signature flags (set to 0 if no signatures)
        $acroForm->set('SigFlags', PdfNumber::int(0));

        $this->acroFormRef = $this->writer->addObject($acroForm);
        return $this->acroFormRef;
    }

    /**
     * Get annotations grouped by page number.
     *
     * @return array<int, array<int, PdfReference>>
     */
    public function getPageAnnotations(): array
    {
        return $this->pageAnnotations;
    }

    /**
     * Get annotations for a specific page.
     *
     * @return array<int, PdfReference>
     */
    public function getAnnotationsForPage(int $page): array
    {
        return $this->pageAnnotations[$page] ?? [];
    }

    /**
     * Get the AcroForm reference.
     */
    public function getAcroFormRef(): ?PdfReference
    {
        return $this->acroFormRef;
    }

    /**
     * Get all field references.
     *
     * @return array<int, PdfReference>
     */
    public function getFieldRefs(): array
    {
        return $this->fieldRefs;
    }

    /**
     * Get font references.
     *
     * @return array<string, PdfReference>
     */
    public function getFontRefs(): array
    {
        return $this->fontRefs;
    }

    /**
     * Check if any fields have been added.
     */
    public function hasFields(): bool
    {
        return !empty($this->fields) || !empty($this->radioGroups);
    }

    /**
     * Get the total number of fields.
     */
    public function getFieldCount(): int
    {
        $count = count($this->fields);
        foreach ($this->radioGroups as $group) {
            $count++; // Count the group as one field
        }
        return $count;
    }

    /**
     * Reset the form writer.
     */
    public function reset(): self
    {
        $this->fields = [];
        $this->radioGroups = [];
        $this->fieldRefs = [];
        $this->pageAnnotations = [];
        $this->fontRefs = [];
        $this->acroFormRef = null;
        return $this;
    }

    /**
     * Create form content for an existing document (incremental update).
     *
     * Returns the objects needed to add form to an existing PDF.
     *
     * @return array{
     *     acroForm: PdfDictionary,
     *     fields: array<int, PdfDictionary>,
     *     appearances: array<int, PdfStream>,
     *     fonts: array<string, PdfDictionary>,
     *     pageAnnots: array<int, array<int, int>>
     * }
     */
    public function buildForIncrementalUpdate(): array
    {
        $result = [
            'acroForm' => null,
            'fields' => [],
            'appearances' => [],
            'fonts' => [],
            'pageAnnots' => [],
        ];

        // Create fonts
        $fonts = [];

        $helvetica = new PdfDictionary();
        $helvetica->set('Type', PdfName::create('Font'));
        $helvetica->set('Subtype', PdfName::create('Type1'));
        $helvetica->set('BaseFont', PdfName::create('Helvetica'));
        $helvetica->set('Encoding', PdfName::create('WinAnsiEncoding'));
        $fonts['Helvetica'] = $helvetica;

        $zapf = new PdfDictionary();
        $zapf->set('Type', PdfName::create('Font'));
        $zapf->set('Subtype', PdfName::create('Type1'));
        $zapf->set('BaseFont', PdfName::create('ZapfDingbats'));
        $fonts['ZapfDingbats'] = $zapf;

        $result['fonts'] = $fonts;

        // Process fields (caller will assign object IDs)
        foreach ($this->fields as $field) {
            $widgetDict = $field->toWidgetDictionary(null);
            $result['fields'][] = $widgetDict;

            $page = $field->getPage();
            if (!isset($result['pageAnnots'][$page])) {
                $result['pageAnnots'][$page] = [];
            }
            $result['pageAnnots'][$page][] = count($result['fields']) - 1;

            // Generate appearance
            $content = $field->generateAppearance();
            if (!empty($content)) {
                $streamDict = new PdfDictionary();
                $streamDict->set('Type', PdfName::create('XObject'));
                $streamDict->set('Subtype', PdfName::create('Form'));
                $streamDict->set('FormType', PdfNumber::int(1));
                $streamDict->set('BBox', PdfArray::fromValues([
                    PdfNumber::real(0),
                    PdfNumber::real(0),
                    PdfNumber::real($field->getWidth()),
                    PdfNumber::real($field->getHeight()),
                ]));
                $streamDict->set('Resources', new PdfDictionary());

                $stream = new PdfStream($streamDict, $content);
                $result['appearances'][] = $stream;
            }
        }

        // Build AcroForm dictionary (references will be set by caller)
        $acroForm = new PdfDictionary();
        $acroForm->set('NeedAppearances', \PdfLib\Parser\Object\PdfBoolean::create(true));
        $acroForm->set('SigFlags', PdfNumber::int(0));
        $acroForm->set('DA', PdfString::literal('/Helv 12 Tf 0 g'));

        $result['acroForm'] = $acroForm;

        return $result;
    }
}
